---
- name: "{{ _version.image_basename }}: Add cmes-utils directory"
  ansible.builtin.copy:
    src: "cmes-utils"
    dest: "{{ _version_cmes_mods_dir }}/"
    mode: "0644"
    group: "{{ cmes_ubuntu_iso_create_group_sticky_gid | int }}"

- name: Create cloud-init folder
  ansible.builtin.file:
    path: "{{ _version_cmes_mods_dir }}/cloud-init"
    state: directory
    mode: "0555"
    group: "{{ cmes_ubuntu_iso_create_group_sticky_gid | int }}"

- name: "{{ _version.image_basename }}: Validate schema"
  ansible.utils.validate:
    data: "{{ lookup('ansible.builtin.template', 'autoinstall.yaml.j2') | from_yaml }}"
    criteria: "{{ lookup('ansible.builtin.file', 'autoinstall_schema.json') }}"
  loop: "{{ cmes_ubuntu_iso_create_install_types }}"
  vars:
    install_type: "{{ item }}"

- name: "{{ _version.image_basename }}: Add cloud-init files for {{ item }} install"
  ansible.builtin.template:
    src: autoinstall.yaml.j2
    dest: "{{ _version_cmes_mods_dir }}/cloud-init/{{ item }}.yaml"
    mode: "0644"
  loop: "{{ cmes_ubuntu_iso_create_install_types }}"
  vars:
    install_type: "{{ item }}"
