---
- name: "{{ _version.version_number }}: Install isolinux menu files for BIOS (legacy) boot"
  ansible.builtin.copy:
    src: "{{ bios_boot_menu_file }}"
    dest: "{{ _version_cmes_mods_dir }}/isolinux/{{ bios_boot_menu_file }}"
    mode: "0644"
  loop_control:
    loop_var: bios_boot_menu_file
  loop:
    - isolinux.cfg
    - cmesmenu.cfg
    - basemenu.cfg

- name: "{{ _version.version_number }}: Install CMES Logo for BIOS (legacy) boot"
  ansible.builtin.copy:
    src: "cmeslogo.{{ _version.version_number }}.png" # Shared with grub (UEFI) boot
    dest: "{{ _version_cmes_mods_dir }}/isolinux/cmeslogo.png"
    mode: "0644"

- name: "{{ _version.version_number }}: Create Menu Configuration for BIOS (legacy) boot"
  ansible.builtin.template:
    src: "isolinux_cmestxt.cfg.jinja"
    dest: "{{ _version_cmes_mods_dir }}/isolinux/cmestxt.cfg"
    mode: "0644"
