---
- name: "{{ _version.version_number }}: Create CMES Files Directory"
  ansible.builtin.file:
    path: "{{ _version_cmes_mods_dir }}/cmes_utils"
    state: directory
    mode: "0555"
    group: "{{ cmes_ubuntu_iso_create_group_sticky_gid | int }}"

- name: "{{ _version.version_number }}: Add CMES Specific Files"
  ansible.builtin.copy:
    src: "bootstrap.sh"
    dest: "{{ _version_cmes_mods_dir }}/cmes_utils"
    mode: "0644"
