---
- name: "{{ _version.version_number }}: Initialize Local ISO File Path"
  ansible.builtin.set_fact:
    _local_iso_file: ""

- name: "{{ _version.version_number }}: Stat Local ISO Files"
  ansible.builtin.stat:
    path: "{{ item }}"
  delegate_to: localhost
  become: false
  register: _stat_iso_file
  loop:
    - "~/Downloads/{{ _version.iso_basename }}.iso"
    - "../../files/{{ _version.iso_basename }}.iso"
    # Note: The last file found will be used

- name: "{{ _version.version_number }}: Set Local ISO File Path"
  ansible.builtin.set_fact:
    _local_iso_file: "{{ _iso_file.item }}"
  when: _iso_file.stat.exists
  loop: "{{ _stat_iso_file.results }}"
  loop_control:
    loop_var: _iso_file

- name: "{{ _version.version_number }}: Make Sure we Found a Local ISO File"
  ansible.builtin.assert:
    that:
      - _local_iso_file | length > 0
    success_msg: "WARNING: Using local ISO file: {{ _local_iso_file }}"
    fail_msg: "ERROR: Local ISO File Not Found!"

- name: "{{ _version.version_number }}: Copy ISO File"
  ansible.builtin.copy:
    src: "{{ _local_iso_file }}"
    dest: "{{ _version_working_dir }}/{{ _version.iso_basename }}.iso"
    mode: 0644
