---
- name: "{{ _version.version_number }}: Extract Master Boot Record from Standard ISO"
  ansible.builtin.command:
    chdir: "{{ _version_working_dir }}"
    cmd: "dd if={{ _version.iso_basename }}.iso of={{ _version.iso_basename }}.mbr bs=1 count={{ _version.iso_mbr_bytes }}"
    creates: "{{ _version_working_dir }}/{{ _version.iso_basename }}.mbr"

- name: "{{ _version.version_number }}: Extract EFI Boot Image from Standard ISO"
  when: _version.version_number > 21
  # The EFI partition is no longer a data file on the ISO
  # So we need extract the EFI partition image from the ISO as well
  block:
    - name: "{{ _version.version_number }}: Find EFI System Partion on Standard ISO"
      ansible.builtin.shell: |
        fdisk -l {{ _version_working_dir }}/{{ _version.iso_basename }}.iso | \
          awk 'NF > 1 && $(NF-1)$NF == "EFISystem" {print "{\"start\": \""$2"\", \"sectors\": \""$4"\"}"}'
      register: _find_iso_efi_partition
      changed_when: false
      check_mode: false

    - name: "{{ _version.version_number }}: Extract EFI System Partion from Standard ISO"
      vars:
        _efi_part: "{{ _find_iso_efi_partition.stdout | from_json }}"
      ansible.builtin.command:
        chdir: "{{ _version_working_dir }}"
        cmd: "dd if={{ _version.iso_basename }}.iso of={{ _version.iso_basename }}.efi.img bs=512 skip={{ _efi_part.start }} count={{ efi_part.sectors }}"
        creates: "{{ _version_working_dir }}/{{ _version.iso_basename }}.efi.img"

- name: "{{ _version.version_number }}: Mount Standard ISO"
  ansible.builtin.mount:
    src: "{{ _version_working_dir }}/{{ _version.iso_basename }}.iso"
    path: "{{ _version_iso_mount_dir }}"
    fstype: iso9660
    fstab: "{{ cmes_ubuntu_iso_create_fstab_temp }}"
    opts: ro,loop
    state: mounted

- name: "{{ _version.version_number }}: Create Modifications Directory"
  file:
    state: directory
    path: "{{ _version_cmes_mods_dir }}"
    group: "{{ cmes_ubuntu_iso_create_group_sticky_gid | int }}"
    mode: 0755

- name: "{{ _version.version_number }}: Extract Directories for Modification"
  ansible.builtin.include_tasks:
    name: extract_ISO_directory.yml
  loop: "{{ cmes_ubuntu_iso_create_modification_directories }}"
  loop_control:
    loop_var: target_dir
