---
- name: "{{ _version.version_number }}: Check for /{{ target_dir }} on ISO"
  ansible.builtin.stat:
    path: "{{ _version_iso_mount_dir }}/{{ target_dir }}"
  register: _iso_source_dir

- name: "{{ _version.version_number }}: Check for /{{ target_dir }} in Modified"
  ansible.builtin.stat:
    path: "{{ _version_cmes_mods_dir }}/{{ target_dir }}"
  register: _modified_dir

- name: "{{ _version.version_number }}: Prepare Mods Directory for /{{ target_dir }}"
  when: _iso_source_dir.stat.exists
  block:
    - name: "{{ _version.version_number }}: Create Mods Directory for /{{ target_dir }}"
      ansible.builtin.file:
        state: directory
        path: "{{ _version_cmes_mods_dir }}/{{ target_dir }}"
        mode: "0555"

    - name: "{{ _version.version_number }}: Synchronize /{{ target_dir }} ISO Content for Modification"
      ansible.posix.synchronize:
        src: "{{ _version_iso_mount_dir }}/{{ target_dir }}"
        dest: "{{ _version_cmes_mods_dir }}"
        archive: true
        times: "{{ not _modified_dir.stat.exists }}"
        compress: false
        delay_updates: false
        rsync_opts:
          - "--exclude='isolinux.cfg'"
          - "--exclude='grub.cfg'"
      delegate_to: "{{ inventory_hostname }}" # This keeps the exchange local (i.e no ssh)
      register: _sync_job_details

    - name: "{{ _version.version_number }}: Show Changes to /{{ target_dir }}"
      # If anything gets overwritten on a second pass, we want to know about it
      debug:
        var: _sync_job_details
      when:
        - _modified_dir.stat.exists
        - _sync_job_details.stdout_lines | length > 0
