---
- name: "{{ _version.image_basename }}: Create Version Working Directory"
  ansible.builtin.file:
    path: "{{ _version_working_dir }}"
    state: directory
    mode: "0775"
    group: "{{ cmes_ubuntu_iso_create_group_sticky_gid | int }}"

- name: "{{ _version.image_basename }}: Include tasks for RaspberryPi"
  when: "'raspi' in _version.arch"
  ansible.builtin.include_tasks: raspi_tasks/main.yml

- name: "{{ _version.image_basename }}: Include tasks for x86_64"
  when: _version.arch == 'x86_64'
  ansible.builtin.include_tasks: x86_64_tasks/main.yml
